---
# tasks file for role_containerd

- name: Install prerequisites
  ansible.builtin.include_tasks: prerequisites.yml

- name: Setup ContainerD from Binaries
  ansible.builtin.include_tasks: setup-binary.yml
  when: containerd_setup_from_binary is defined and containerd_setup_from_binary

- name: Setup ContainerD from Repo
  ansible.builtin.include_tasks: setup-repo.yml
  when: containerd_setup_from_repo is defined and containerd_setup_from_repo
