---
# tasks file for role_containerd

- name: Install prerequisites
  ansible.builtin.include_tasks: prerequisites.yml

- name: Setup ContainerD
  ansible.builtin.include_tasks: setup-{{ containerd_setup_type }}.yml

- name: Setup ContainerD Configuration
  ansible.builtin.include_tasks: post-tasks.yml
