---
# tasks file for role_containerd

- name: Install Prerequisite Packages
  ansible.builtin.include_tasks: prerequisites.yml

- name: Setup Containerd runtime
  ansible.builtin.include_tasks: "{{ containerd_setup_type }}/main.yml"

- name: Setup Containerd Configuration
  ansible.builtin.include_tasks: post-tasks.yml
