---

- name: Set architecture if not defined
  ansible.builtin.set_fact:
    containerd_architecture: "{{ containerd_architecture | default('amd64') }}"
  delegate_to: localhost
  become: false
  run_once: true

- name: Set download URLs and filenames for each component
  ansible.builtin.set_fact:
    # Containerd binary and verification
    containerd_binary:
      url: "https://github.com/containerd/containerd/releases/download/{{ containerd_tag }}/containerd-{{ containerd_version }}-linux-{{ containerd_architecture }}.tar.gz"
      filename: "containerd-{{ containerd_version }}-linux-{{ containerd_architecture }}.tar.gz"
      type: "binary"
    containerd_verification:
      url: "https://github.com/containerd/containerd/releases/download/{{ containerd_tag }}/containerd-{{ containerd_version }}-linux-{{ containerd_architecture }}.tar.gz.sha256sum"
      filename: "containerd-{{ containerd_version }}-linux-{{ containerd_architecture }}.tar.gz.sha256sum"
      type: "checksum"
    
    # Runc binary and verification
    runc_binary:
      url: "https://github.com/opencontainers/runc/releases/download/{{ runc_tag }}/runc.{{ containerd_architecture }}"
      filename: "runc.{{ containerd_architecture }}"
      type: "binary"
    runc_verification:
      url: "https://github.com/opencontainers/runc/releases/download/{{ runc_tag }}/runc.{{ containerd_architecture }}.asc"
      filename: "runc.{{ containerd_architecture }}.asc"
      type: "signature"
    
    # CNI plugins binary and verification
    cni_plugins_binary:
      url: "https://github.com/containernetworking/plugins/releases/download/{{ cni_plugins_tag }}/cni-plugins-linux-{{ containerd_architecture }}-{{ cni_plugins_tag }}.tgz"
      filename: "cni-plugins-linux-{{ containerd_architecture }}-{{ cni_plugins_tag }}.tgz"
      type: "binary"
    cni_plugins_verification:
      url: "https://github.com/containernetworking/plugins/releases/download/{{ cni_plugins_tag }}/cni-plugins-linux-{{ containerd_architecture }}-{{ cni_plugins_tag }}.tgz.sha256"
      filename: "cni-plugins-linux-{{ containerd_architecture }}-{{ cni_plugins_tag }}.tgz.sha256"
      type: "checksum"
