---

- name: Download containerd binary file
  ansible.builtin.get_url:
    url: "{{ containerd_binary.url }}"
    dest: "{{ containerd_service_binary_path }}/{{ containerd_binary.filename }}"
    mode: '0644'

- name: Download containerd verification file
  ansible.builtin.get_url:
    url: "{{ containerd_verification.url }}"
    dest: "{{ containerd_service_binary_path }}/{{ containerd_verification.filename }}"
    mode: '0644'

- name: Extract containerd
  ansible.builtin.unarchive:
    src: "{{ containerd_service_binary_path }}/{{ containerd_binary.filename }}"
    dest: "{{ containerd_service_binary_path }}/"
    remote_src: yes
