---

- name: Set repository distribution name
  ansible.builtin.set_fact:
    repo_distribution: >-
      {% if ansible_distribution in ['CentOS', 'Fedora', 'RedHat', 'AlmaLinux', 'Rocky'] %}rhel
      {% else %}{{ ansible_distribution | lower }}{% endif %}

- name: Remove existing Docker repository file (RedHat family)
  ansible.builtin.file:
    path: /etc/yum.repos.d/docker-ce.repo
    state: absent
  become: true

- name: Install dnf-plugins-core (RedHat family)
  ansible.builtin.dnf:
    name:
      - dnf-plugins-core
      - yum-utils
      - glibc
    state: present
  become: true

- name: Add Docker repository (RedHat family)
  ansible.builtin.shell: dnf config-manager --add-repo "https://download.docker.com/linux/{{ repo_distribution | trim }}/docker-ce.repo"
  args:
    executable: /bin/bash
  become: true
  register: add_repo_result
  changed_when: add_repo_result.rc == 0

- name: Install containerd.io package
  ansible.builtin.dnf:
    name:
      - containerd.io
      - containernetworking-plugins
    state: present
  become: true

- include_tasks: systemd-service.yml

- name: Enable and start containerd service
  ansible.builtin.systemd:
    name: containerd
    state: started
    enabled: yes
  become: true
