---

- name: set repository distribution name
  ansible.builtin.set_fact:
    repo_distribution: >-
      {% if ansible_distribution in ['CentOS', 'Fedora', 'RedHat', 'AlmaLinux', 'Rocky'] %}rhel
      {% else %}{{ ansible_distribution | lower }}{% endif %}

- name: install dnf-plugins-core (RedHat family)
  ansible.builtin.dnf:
    name:
      - dnf-plugins-core
      - yum-utils
      - glibc
    state: present

- name: download docker repository file (RedHat family)
  ansible.builtin.get_url:
    url: "https://download.docker.com/linux/{{ repo_distribution | trim }}/docker-ce.repo"
    dest: /etc/yum.repos.d/docker-ce.repo
    mode: '0644'
    owner: root
    group: root

- name: check if containernetworking-plugins package is available
  ansible.builtin.command:
    cmd: "dnf --quiet list available containernetworking-plugins"
  register: cnp_avail
  failed_when: false
  changed_when: false

- name: set packages to install for RedHat
  ansible.builtin.set_fact:
    containerd_install_pkgs: >-
      {{ ['containerd.io'] + ((cnp_avail is defined and cnp_avail.rc == 0) | ternary(['containernetworking-plugins'], [])) }}

- name: install containerd.io package
  ansible.builtin.dnf:
    name: "{{ containerd_install_pkgs }}"
    state: present
